<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Survey Report - {{ $survey->title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        h1 {
            color: #696cff;
            font-size: 24px;
            margin-bottom: 5px;
        }
        h2 {
            font-size: 16px;
            color: #566a7f;
            margin-top: 20px;
            border-bottom: 2px solid #696cff;
            padding-bottom: 5px;
        }
        .header {
            margin-bottom: 30px;
        }
        .info-box {
            background: #f8f9fa;
            padding: 10px;
            margin-bottom: 20px;
            border-left: 4px solid #696cff;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th, table td {
            padding: 8px;
            text-align: left;
            border: 1px solid #ddd;
        }
        table th {
            background-color: #696cff;
            color: white;
        }
        .section {
            margin-bottom: 30px;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 10px;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $survey->title }}</h1>
        <p><strong>Report Generated:</strong> {{ now()->format('d/m/Y H:i:s') }}</p>
        <p><strong>Date Range:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d/m/Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('d/m/Y') }}</p>
    </div>

    <div class="info-box">
        <strong>Total Responses:</strong> {{ $totalResponses }}
    </div>

    @foreach($statistics as $stat)
        <div class="section">
            <h2>{{ $stat['question'] }}</h2>
            <p><strong>Question Type:</strong> {{ ucfirst($stat['type']) }}</p>
            <p><strong>Total Answers:</strong> {{ $stat['total_responses'] }}</p>

            @if(isset($stat['average']))
                <p><strong>Average Rating:</strong> {{ $stat['average'] }} / 5</p>
            @endif

            @if(isset($stat['breakdown']))
                <table>
                    <thead>
                        <tr>
                            <th>Answer</th>
                            <th>Count</th>
                            <th>Percentage</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($stat['breakdown'] as $answer => $count)
                            <tr>
                                <td>{{ $answer }}</td>
                                <td>{{ $count }}</td>
                                <td>{{ $stat['total_responses'] > 0 ? round(($count / $stat['total_responses']) * 100, 1) : 0 }}%</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    @endforeach

    <div class="footer">
        <p>Generated by Survey System &copy; {{ now()->year }}</p>
    </div>
</body>
</html>
